#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

#define POSITION_ATTRIB_LOCATION 0
#define TEXCOORD_ATTRIB_LOCATION 1
#define NORMAL_ATTRIB_LOCATION 2
#define COLOR_ATTRIB_LOCATION 3
#define POSITION_SIZE_ATTRIB_LOCATION 4
#define TEX_INDEX_ATTRIB_LOCATION 5

#define LIFE_TIME_LOCATION 6

#define MAX_POINT_LIGHTS 4

#endif
